### ISSUE TITLE
Make it clearer that roles, environments etc. need to be json, not rb!

### ISSUE THREAD

**Issue by edmundcraske** [chef/chef-zero#107]
Hi, I may be missing something, but I did not see anywhere in any documentation that roles and environments need to be in json format for chef-zero to pick them up. Even running in debug mode, there are no messages explaining why I get a 404. It would be nice if it was made clearer, and even nicer if chef-zero noticed the presence of .rb files without .json files and spat out an INFO message saying that .rb will not work...

**Comment by rmoriz** [comment]
:+1:

**Comment by ChrisLundquist** [comment]
Please! :+1:

**Comment by JoeReid-Korrelate** [comment]
+1 

I'd like it either way.  Either better documentation on what needs to be in .json, or fix chef-zero to read environments, roles, etc. written in the ruby DSL format.  

I could be wrong, but don't both chef solo and chef server support the ruby format?

**Comment by cullenmcdermott** [comment]
@Joseph-R you are correct, both support ruby(all of my roles and envs are in ruby currently). I'd really like it if chef-zero could use roles written in Ruby if possible.

**Comment by realloc** [comment]
+1 for Ruby DSL support.
Currently we use wrapper that converts .rb to .json on every deploy and it's a pain.

**Comment by pmahoney** [comment]
@dwradcliffe wrote
> Is there a reason this don't read .rb files? We have all our roles in git as ruby and it's going to be a pain to convert them all for testing.

Any followup on this? I assume it's not trivial for chef-zero to support the .rb format? Or is there another reason?

**Comment by gsaslis** [comment]
This would definitely be good to have

**Comment by thommay** [comment]
If you use chef-zero with cheffs as the filesystem (ie, what `knife-serve` does by default), ruby roles and environments are now supported. I'm not sure there's much else needed here?

**Comment by mrjcleaver** [comment]
@thommay are you saying Ruby Roles are now supported by default? Thanks, M.

**Comment by gsaslis** [comment]
@thommay yeah - would you plz help clarify the whole cheffs comment plz? :)

**Comment by jason-riddle** [comment]
If it it supported, a link to the line in the documentation would be great as well.

**Comment by thommay** [comment]
By default, chef-zero has no knowledge of _chef_; it simply serves json files off the filesystem. If you simply run `chef-zero`, ruby roles and environments are not - and should not be - supported.

However, chef-zero has support for pluggable backend implementations. The `ChefFS` backend, which we ship in chef itself, and which `knife serve` uses, does understand chef objects, and is capable of reading ruby files and serving them as json. See the documentation for [knife serve](https://docs.chef.io/knife_serve.html) for more information.

I'm happy to add something to the readme documenting this case if necessary.

**Comment by jason-riddle** [comment]
> By default, chef-zero has no knowledge of chef; it simply serves json files off the filesystem. If you simply run chef-zero, ruby roles and environments are not - and should not be - supported.

Where is this stated, other than in this github issue? Why would I, as an end user, expect my ruby roles and ruby environment files not to work with another chef product? That's all I'm saying. Up till you said that I had no idea that chef zero is just serving json files off the filesystem, but maybe that's my fault if I misread something on the documentation, which is why I'm asking for a link. It has come up in some issues (https://github.com/chef/chef/issues/2502, https://github.com/mitchellh/vagrant/issues/6159) but yet it seems to not be officially documented anywhere and it's not always clear for new comers what to search for.

**Comment by mrjcleaver** [comment]
It's confusing, not least because Chef Generators creates a README that says:
`Create roles here, in either the Role Ruby DSL (.rb) or JSON (.json) files. To install roles on the server, use knife.
`

**Comment by gsaslis** [comment]
I have to agree with @jason-riddle and @mrjcleaver - this is definitely confusing, and this issue was not really about ruby roles being supported or not, but rather about making it *clear* if they are supported or not (and under what circumstances). 

@thommay your explanation here certainly does help a little, but, imho, it assumes whoever's reading it already knows a lot about chef, to even be able to understand it.. 

I think a simpler explanation should be added in the docs for anyone who's just trying to write their first cookbook and e.g. test it with test-kitchen, using chef-zero.
