### ISSUE TITLE
Newlines in chef searches work in chef-zero, but not in chef (11)

### ISSUE THREAD

**Issue by wolftrouble** [chef/chef-zero#122]
I ran into a situation today where while testing with Kitchen a search that was split across multiple lines was functioning fine, but in production throws a 400 Bad Request. This is because newlines in searches are not allowed in Chef 11: https://github.com/chef/chef-docs/commit/7cdd02f17616bb4c4370bc0bfa4e372cc689cd6a.

I'm able to reproduce this trivially easy: Any search that's split across lines, e.g.

search(:node, "somesearch"
            AND "some other search)

will reliably work with chef-zero, and reliably fail with chef v11.18.6.

I know the README specifically says chef-zero will not throw 400s, but arguably the fact that the recipe compiles at all under Chef 11 should be a bug (against Chef) in and of itself. The 400 is thrown only because Chef isn't handling what should be a syntax error at the compile phase.

**Comment by jeremiahsnapp** [comment]
/cc @jkeiser @lamont-granquist Would one of the engineers mind providing some feedback on this please? Since the README says chef-zero will not respond with a 400 or do input validation it seems like no work is necessary here but confirmation would be great.

I think this basic syntax checking should be done by Foodcritic. Rule [FC010: invalid search syntax](http://acrmp.github.io/foodcritic/#FC010) already tests search syntax. It just needs to be modified so it also looks for newlines so I opened the following issue for that.

https://github.com/acrmp/foodcritic/issues/341

**Comment by jkeiser** [comment]
This is not a priority to fix in Chef Zero, because of the explicit lack of validation (a rule that exists to keep the code simple to work with). Food critic is a reasonable place if the queries are static; the Chef server is a good place to fix it if queries with newlines are part of lucene syntax.

**Comment by lamont-granquist** [comment]
Yeah, they're all fine places to fix it, but the priority of this issue is going to be low.

There seems like there might be an implicit bug request here to make chef-zero a perfect bug-compatible chef-server so that if you run a recipe under TK with chef-zero that it will be guaranteed to work correctly on a real chef-server, and I don't think we can agree to that.  TK plus chef-zero will always just strive for "pretty good", but if you're looking for production validation you really must push your code to an integration/acceptance/whatever kind of environment before production.

**Comment by lamont-granquist** [comment]
Yeah I think we shouldn't be deliberately introducing bugs into chef-zero.  If this is still a bug in server 12.x it should get fixed there.

**Comment by wolftrouble** [comment]
I guess I don't really understand how an intentionally-introduced behavior in the Chef server (note my link is to a commit, not an issue) qualifies as a "bug", and I'd think "behavior" parity with the server is something to strive for on things like basic syntax. I'm sympathetic to the argument that "good enough" is the goal because that's just what's possible, but if something as basic as syntax is valid in chef-zero and invalid on the chef server I'd argue it's *not* good enough.

I'd also say this problem is doubly bad because it's not as if chef-zero is being "stricter" than the server - it's the opposite. I'd much prefer to have code that should be valid on the server failing in chef-zero than have code that's valid in chef-zero failing on the server.

You're basically now just maintaining your own fork of the Chef DSL (irrespective that it used to be valid in the server, it's not anymore, and that's by design). That seems non-optimal and at odds with the whole point of chef-zero.

Anyway, thanks for the response.
