### ISSUE TITLE
check if a data_bag exists

### ISSUE THREAD

**Issue by engel75** [chef/chef-zero#207]
Is there any method to check if a databag does exist?

I tried

`if data_bag(:mariadb)`

but chef-zero fails with 

` Net::HTTPServerException
       ------------------------
       404 "Not Found"
`

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/opscode/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
