### ISSUE TITLE
Knife Search throwing error

### ISSUE THREAD

**Issue by tejaycar** [chef/chef-zero#60]
When I run a knife search, ANY knife search it seems, I get back a stacktrace indicating `TypeError: can't convert Fixnum into String` throwing from `TypeError: can't convert Fixnum into String'

Adding a cast to `term[index].to_s' on line 32 fixes the error, but results in no results being returned from the search, even when there are valid results available.

You can reproduce the TypeError with the vagrantfile and knife.rb located here:
https://github.com/tejaycar/chef-zero/tree/master/chef-zero-test

**Comment by thommay** [comment]
I'm sorry that this ticket has languished in the wilderness for so long, but since the last activity was two years ago and this seems to be a ruby 1.8 -> 1.9 bug, I think we can safely close it. If this seems unreasonable (or you're still seeing this occur in a supported ruby), please feel free to reopen this ticket.
Thanks for the report!
